In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Session 3 - The making of Pandas data frames


<img src="img/company-logo.png" width=120 height=120 align="right">

Author: Prof. Manoel Gadi

Contact: manoelgadi@gmail.com

Teaching Web: http://mfalonso.pythonanywhere.com

Linkedin: https://www.linkedin.com/in/manoel-gadi-97821213/

Github: https://github.com/manoelgadi

Last revision: 27/October/2022


## 1.0 - Numpy 

<img src="img/Numpy1.png" width=600 height=500 align="left">

<img src="img/Numpy2.png" width=600 height=500 align="left">

<img src="img/Numpy3.png" width=600 height=500 align="left">

Travis Oliphant is an American data scientist and businessman. He is founder of technology startup Anaconda. In addition, he is the primary creator of NumPy and founding contributor to the SciPy packages in the Python programming languages.
ref: https://en.wikipedia.org/wiki/Travis_Oliphant

Numpy arrays can be 1D, 2D, 3D, ... N-Dimension, let´s have a look at 2D:


<img src="img/np_array.png" width=500 height=400 align="left">

* The number of dimensions is known as the rank of the array
* The shape of an array is a tuple of integers giving the size of the array along each dimension
* The index refers to the position of a value in the array. In Python, indexing starts at 0.


## 1.1 Practicing Numpy via exercises

Where can I learn more about Numpy? https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

# 2. Pandas

Now we have all the ingredients to create one of the most powerful data structures of all, the DATA FRAME.

For this we will need:
    * 2 Lists
    * 2 Dictionaries
    * and many 1D numpy arrays

## 2.1 Pandas Data Frame Structure

<img src="img/pandas_df_structure.png" align="left">

Let's firs import pandas using the alias (or nickname) 'pd'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame(np.random.randn(10,4))
print(df)

          0         1         2         3
0  0.762643  1.380487  1.027665 -0.423070
1  1.600011  1.347830 -1.572619  0.515659
2 -0.269411 -0.386952  0.637001  0.235059
3 -0.492615  0.165268  0.677506  0.580209
4  1.149133  1.807381 -0.669982  0.774252
5  0.943741 -0.932524 -0.275798 -0.563353
6  0.181623 -0.149857  1.074561  2.119868
7  0.190805  0.381999 -0.072820 -0.722209
8  2.789091  0.691060 -0.535376  2.456895
9 -0.351469  0.148721 -0.536216  0.736286


In [4]:
# df['A']

In [5]:
df=pd.DataFrame(np.random.randn(10,4),columns=['A','B','C','D'])
print(df)

          A         B         C         D
0 -1.303255  0.699744 -0.724751  1.066354
1 -1.548348 -0.084987  0.829938  1.052621
2  0.870302  0.043481 -0.887181 -0.024244
3  0.336638  1.194613 -0.190462  0.286961
4 -0.096758  1.481669 -0.679433  0.043293
5 -0.295857 -0.212238  1.010791  0.909572
6 -0.934843 -1.417983 -0.947026 -0.708081
7  0.340230 -1.471410 -0.134417 -0.951272
8  0.074139  1.438235 -0.715659  0.040178
9  0.636494  1.957226 -0.788561  0.104597


In [6]:
df['A']

0   -1.303255
1   -1.548348
2    0.870302
3    0.336638
4   -0.096758
5   -0.295857
6   -0.934843
7    0.340230
8    0.074139
9    0.636494
Name: A, dtype: float64

In [7]:
df=pd.DataFrame(np.random.randn(10,4),columns=['A','B a l l','C','D'],index=['row0', 'row1', 'row2', 'row3', 'row4', 'row5', 
                                                                       'row6', 'row7', 'row8', 'row9'])
print(df)

             A   B a l l         C         D
row0 -1.677648  0.796749 -0.084687  0.313714
row1  0.706630 -1.555183  0.579712  2.326993
row2 -0.651134 -0.205622 -2.182288  1.821328
row3  1.824697 -0.780913 -0.418773  0.217954
row4 -2.001827  0.223153 -1.590659 -1.006255
row5 -0.508658  0.362282  0.017476  0.403520
row6  1.188983 -1.057014  0.701907  1.833508
row7 -0.853101 -1.024936 -0.391805  0.381026
row8 -0.067996  0.334960 -0.774354  0.079186
row9  0.175510 -0.573544 -1.262235  0.121385


Selection column 'B' using its name, in other words, using the dictionary!

In [8]:
df.A

row0   -1.677648
row1    0.706630
row2   -0.651134
row3    1.824697
row4   -2.001827
row5   -0.508658
row6    1.188983
row7   -0.853101
row8   -0.067996
row9    0.175510
Name: A, dtype: float64

In [9]:
#df.B a l l #equivalent to df.loc[:,'B'] - LOC is for accessing the DICTIONARY of labels.
df['B a l l'] #df.loc[rows,columns]

row0    0.796749
row1   -1.555183
row2   -0.205622
row3   -0.780913
row4    0.223153
row5    0.362282
row6   -1.057014
row7   -1.024936
row8    0.334960
row9   -0.573544
Name: B a l l, dtype: float64

In [10]:
df['B a l l']

row0    0.796749
row1   -1.555183
row2   -0.205622
row3   -0.780913
row4    0.223153
row5    0.362282
row6   -1.057014
row7   -1.024936
row8    0.334960
row9   -0.573544
Name: B a l l, dtype: float64

Selection column 'B' using its position, in other words, using the list!

In [11]:
print(df)

             A   B a l l         C         D
row0 -1.677648  0.796749 -0.084687  0.313714
row1  0.706630 -1.555183  0.579712  2.326993
row2 -0.651134 -0.205622 -2.182288  1.821328
row3  1.824697 -0.780913 -0.418773  0.217954
row4 -2.001827  0.223153 -1.590659 -1.006255
row5 -0.508658  0.362282  0.017476  0.403520
row6  1.188983 -1.057014  0.701907  1.833508
row7 -0.853101 -1.024936 -0.391805  0.381026
row8 -0.067996  0.334960 -0.774354  0.079186
row9  0.175510 -0.573544 -1.262235  0.121385


In [12]:
df.iloc[1:4,1:3] # second column of data frame (last_name) - : = all rows of column 1 (list index starts from 0) 
#  - ILOC is for accessing the LIST of indexes.

B a l l         C
row1 -1.555183  0.579712
row2 -0.205622 -2.182288
row3 -0.780913 -0.418773

Selecting the second row using its name 'row1', in other words, using the dictionary!

In [13]:
df['C']

row0   -0.084687
row1    0.579712
row2   -2.182288
row3   -0.418773
row4   -1.590659
row5    0.017476
row6    0.701907
row7   -0.391805
row8   -0.774354
row9   -1.262235
Name: C, dtype: float64

In [14]:
df.loc['row1','C']

0.5797116451764093

Selecting the second row using its position or index, in other words, using the list!

In [15]:
df

A   B a l l         C         D
row0 -1.677648  0.796749 -0.084687  0.313714
row1  0.706630 -1.555183  0.579712  2.326993
row2 -0.651134 -0.205622 -2.182288  1.821328
row3  1.824697 -0.780913 -0.418773  0.217954
row4 -2.001827  0.223153 -1.590659 -1.006255
row5 -0.508658  0.362282  0.017476  0.403520
row6  1.188983 -1.057014  0.701907  1.833508
row7 -0.853101 -1.024936 -0.391805  0.381026
row8 -0.067996  0.334960 -0.774354  0.079186
row9  0.175510 -0.573544 -1.262235  0.121385

In [16]:
df.iloc[1] # second row of data frame using

A          0.706630
B a l l   -1.555183
C          0.579712
D          2.326993
Name: row1, dtype: float64

In [17]:
a = [0,1,2,3,4,5,6,7]

In [18]:
a[0:3]

[0, 1, 2]

In [19]:
df.iloc[1:10]['A']

row1    0.706630
row2   -0.651134
row3    1.824697
row4   -2.001827
row5   -0.508658
row6    1.188983
row7   -0.853101
row8   -0.067996
row9    0.175510
Name: A, dtype: float64

In [20]:
df2 = df.iloc[1:10]
df2['A']

row1    0.706630
row2   -0.651134
row3    1.824697
row4   -2.001827
row5   -0.508658
row6    1.188983
row7   -0.853101
row8   -0.067996
row9    0.175510
Name: A, dtype: float64

## 2.2 Slicing

__ As .iloc access via list, and as we are specialists in list already ;-) - we can use the power of slicing to do cool things: __

__ Rows: __
* df.iloc[0] # first row of data frame
* df.iloc[1] # second row of data frame
* df.iloc[-1] # last row of data frame

__ Columns: __ 
* df.iloc[:,0] # first column of data frame
* df.iloc[:,1] # second column of data frame
* df.iloc[:,-1] # last column of data frame

In [21]:
a


[0, 1, 2, 3, 4, 5, 6, 7]

In [22]:
a[1:6:2]

[1, 3, 5]

In [23]:
# Remember, double colon :: allows us to set the step we wish to select.
print(df.iloc[0::2]) #Starts from 0 and gets all the EVEN rows.

             A   B a l l         C         D
row0 -1.677648  0.796749 -0.084687  0.313714
row2 -0.651134 -0.205622 -2.182288  1.821328
row4 -2.001827  0.223153 -1.590659 -1.006255
row6  1.188983 -1.057014  0.701907  1.833508
row8 -0.067996  0.334960 -0.774354  0.079186


In [24]:
print(df.iloc[1::2]) #Starts from 0 and gets all the ODD rows.

             A   B a l l         C         D
row1  0.706630 -1.555183  0.579712  2.326993
row3  1.824697 -0.780913 -0.418773  0.217954
row5 -0.508658  0.362282  0.017476  0.403520
row7 -0.853101 -1.024936 -0.391805  0.381026
row9  0.175510 -0.573544 -1.262235  0.121385


In [25]:
print(df.iloc[:,0::2]) #Starts from 0 and gets all the EVEN columns.

             A         C
row0 -1.677648 -0.084687
row1  0.706630  0.579712
row2 -0.651134 -2.182288
row3  1.824697 -0.418773
row4 -2.001827 -1.590659
row5 -0.508658  0.017476
row6  1.188983  0.701907
row7 -0.853101 -0.391805
row8 -0.067996 -0.774354
row9  0.175510 -1.262235


In [26]:
print(df.iloc[:,1::2]) #Starts from 1 and gets all the ODD columns.

       B a l l         D
row0  0.796749  0.313714
row1 -1.555183  2.326993
row2 -0.205622  1.821328
row3 -0.780913  0.217954
row4  0.223153 -1.006255
row5  0.362282  0.403520
row6 -1.057014  1.833508
row7 -1.024936  0.381026
row8  0.334960  0.079186
row9 -0.573544  0.121385


## Exercise:

__print that would return all the EVEN rows and all the ODD columns of df!!!__ 



Great job, from now on, we are ready to start doing serious things with Python using this power Data Structure that brings __VELOCITY, VOLUME AND VARIETY__ to the table.

## 2.4 Practicing Pandas via exercises

Where can I learn more about Pandas? https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles-with-solutions.ipynb

---
# EXTRA MATERIAL - 

## 2.5 - A bit of Pandas history

Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

Pandas began as a project in 2008 to join together a specific set of requirements that were not found together on any tool.

The author Wes McKinney was working at the investment fund AQR Capital Management at the time, he found in Numpy and in basic Python all the ingredients to put together a Data Structure as powerfull as its rivals SAS .sas7bdat and MATLAB .mat propretary data formats. 



<img src="img/WesMcKinney.png" align="left">

Working in stock trading means BIG DATA - Variety, Velocity and Volume.

* Variety: Pandas uses independent Numpy arrays to allow variety.
* Velocity: Pandas is in-memory data format, allowing much faster computation than early rivals.
* Volume: Computer disk swap allows pandas to use memory and disk to hold huge data sets.


What else comes with pandas?

* Data structures with labeled axes
* Time series functionalities
* Same data structures for both time-series and non-time series data
* Arithmetic operations based on labels
* Flexible handling of missing data
* Merge and relational operations (like in SQL)

Today, it has grown into one of the most important Data Analysis libraries!

* Actively supported by a community from around the world
* Is the go-to library for high-performance, easy-to-use data structures and data analysis tools 
* Is a project sponsored by NumFOCUS, same as:


<img src="img/np_mat_jup.png" width=500 height=400 align="left">

---

## 3. More material - Recap on LISTS and more on Numpy

In [27]:
a = [0,1,2,3,4,5] #this creates a basic numeric list (also known as a vector or one-dimensional array) 
print("List a: " + str(a))

b = ['a', 'b', 'c'] #this creates a list of strings
print("List b: " + str(b))

c = [[0,1,2,3],[4,5,6],[7,8,9]] #you can also create a list of lists
print("List c: " + str(c))

d = ['cat', 2] #a list can include many different data types
print("List d: " + str(d))

List a: [0, 1, 2, 3, 4, 5]
List b: ['a', 'b', 'c']
List c: [[0, 1, 2, 3], [4, 5, 6], [7, 8, 9]]
List d: ['cat', 2]


1.1 List slicing

In [28]:
#a[w:s] - Wait w elements, start copy (:), stop before reaching index s

In [29]:
print(a[2:4]) # Wait 2 elements (position 1 as lists start from 0), start copy (:), stop before reaching index 4 (position 3, as it will go to n-1)

[2, 3]


In [30]:
print(a[2:]) # Wait 2 element, start copy (:), stop before reaching index s, the DEFAULT behaviour if "s" is omitted is until the end.

[2, 3, 4, 5]


In [31]:
print(a[:2]) # if "w" is omitted the DEFAULT behaviour is wait 0 elements, start copy (:), stop before reaching index 2

[0, 1]


In [32]:
# double colon :: allows us to set the step to select.
print(a[0::2]) #Starts from 0 and gets all the EVEN positions.
print(a[::2])

[0, 2, 4]
[0, 2, 4]


In [33]:
print(a[1::2]) #Starts from 0 and gets all the ODD positions.

[1, 3, 5]


## 3.2 Numpy

<img src="img/scipy_ecosystem.png" width=500 height=400 align="left">

In [34]:
import numpy as np

## 3.3 Lists vs. arrays


Let's mutiply list 'a' by 3. Then, let's do the same after transforming variable 'a' into an array.

In [35]:
a3 = a*3
print(a3)
np_a3=np.array(a)*3
print(np_a3)

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
[ 0  3  6  9 12 15]


3.1 Numpy slicing works exactly the same as list slicing!

In [36]:
print(np_a3[2:4]) # Wait 2 elements, start copy (:), stop before reaching index 4

[6 9]


In [37]:
np_a3[1::2] #Starts from 0 and gets all the ODD positions.

array([ 3,  9, 15])

## 3.4 Inspecting your NumPy array

Let's find out the size, dimension, and length of variable 'c':

First with 'c' as a list:

In [38]:
c = [[0,1,2,3],[4,5,6],[7,8,9]]

In [39]:
#c.size

Secondly with 'c' as an array:

In [40]:
c = np.array(c)
print(c.size)
print(c.shape)
print(c.ndim)
print(len(c))

3
(3,)
1
3


C:\Users\manoe\AppData\Local\Temp\ipykernel_13420\500310125.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c = np.array(c)


Now, let's find out the type of elements inside array a,b,c

In [41]:
a = np.array(a)
b = np.array(b)
c = np.array(c)
print(a.dtype, b.dtype, c.dtype)

int32 <U1 object


How do you find out if the 'a' variable is a NumPy array?

In [42]:
print(type(a))

<class 'numpy.ndarray'>


Let's transform the data type of 'a' from integer to string, then assign it to a list, called 'la'

In [43]:
a = a.astype('U')
la = a.tolist()
print(type(a))
print(type(la))

<class 'numpy.ndarray'>
<class 'list'>


## 3.5 Selecting data from your NumPy array 

In [44]:
z = [[180, 70],
[200, 72],
[220, 75],
[250, 80]] # Create an array with 4 rows and 2 columns

np_z = np.array(z) # Convert it the array using numpy

Let's try to find out:
- z1 value in second row and second column
- z2 values in the first 3 rows
- z3 first three values in the first column

In [45]:
z1 = np_z[1,1]
z2 = np_z[:3]
z3 = np_z[:3,1]
print(z1)
print(z2)
print(z3)

72
[[180  70]
 [200  72]
 [220  75]]
[70 72 75]


## 3.6 Math with your NumPy Array

In [46]:
a = np.array([1,2,3,10]) #create the first array a
b = np.array([10,10,10,10]) #create the second array b

Let's add 'a' and 'b' together and return the square root of it

In [47]:
ab = np.add(a,b)
print(ab)
print(np.sqrt(ab))

[11 12 13 20]
[3.31662479 3.46410162 3.60555128 4.47213595]


## 3.7 Manipulating your NumPy array

In [48]:
oneD = np.array([1,2,3])
twoD = np.array([(4,5,6), (7,8,9)]) # Dimension (2,3)

Let's transpose the twoD array into a new array called twoD_t:

In [49]:
print(twoD)
twoD_t = np.transpose(twoD)
print(twoD_t)

[[4 5 6]
 [7 8 9]]
[[4 7]
 [5 8]
 [6 9]]


Let's append oneD and twoD together

In [50]:
print(np.append(oneD, twoD))

[1 2 3 4 5 6 7 8 9]


## 3.8 Statistical methods using NumPy

Let's find out the mean, min and max of twoD, with the min and max assigned to the variable tmin and tmax:

In [51]:
print(np.mean(twoD))
tmin = twoD.min()
tmax = twoD.max()
print(tmin)
print(tmax)

6.5
4
9


---